### PR TITLE
Scenario added and also tag progression used in runners class not progression class

### PR DESCRIPTION
**Pull request by RuthBerhane**

### CODE REVIEW

**Review by DavidSwavey — APPROVED** [review]
Good work! Looks good.

**Review by arthuroLP — APPROVED** [review]
Reviewed Changes

**Review by matakevin — APPROVED** [review]
LGTM

**Review by matakevin — APPROVED** [review]
Updated scripts to include screenshots, doesn't impact anyone's test cases so it still LGTM

**Review by chromatechacademy — APPROVED** [review]

**Review by JOYCE-CAG — APPROVED** [review]
Looks Great

**Pull request merged**
