### PR TITLE
Handled the login for both the admin and student sites of the chroma …

### PR DESCRIPTION
**Pull request by safwan216**
…tech real estate system with the credentials of the student site as the only blocker

### CODE REVIEW

**Review by DavidSwavey — APPROVED** [review]
Looks good!

**Review by JOYCE-CAG — APPROVED** [review]
Great Job Safwan

**Review by RuthBerhane — APPROVED** [review]

**Review by zimaxleto — APPROVED** [review]
reviewed

**Review by SergNikole — APPROVED** [review]

**Review by arthuroLP — APPROVED** [review]
Looks fine

**Review by matakevin — APPROVED** [review]

**Review by ulyanamazur — APPROVED** [review]

**Review by ulyanamazur — APPROVED** [review]

**Review by ulyanamazur — APPROVED** [review]

**Review by ulyanamazur — APPROVED** [review]

**Pull request merged**
