### PR TITLE
Safwan

### PR DESCRIPTION
**Pull request by safwan216**
I have added the modules for "Add Homework", "Edit Student", "Create an agent" and "Delete Agent" modules

### CODE REVIEW

**Review by matakevin — COMMENTED** [review]
Add the comments on the RealEstateAgentsPage and I think it looks good

**Review by JOYCE-CAG — APPROVED** [review]
You did a Great job Safwan

**Review by matakevin — APPROVED** [review]
Looks good to me.  Thank you for changing the comments in your pages class

**Review by zimaxleto — APPROVED** [review]
Reviewed

**Review by DavidSwavey — APPROVED** [review]
Looks good. Great work!

**Review by arthuroLP — APPROVED** [review]

**Review by RuthBerhane — COMMENTED** [review]
On your PageInitializer you commented and referred to Locators, but these aren't locators, can you change the comments, otherwise great job!

**Review by SergNikole — APPROVED** [review]

**Review by RuthBerhane — APPROVED** [review]

**Pull request merged**
