### PR TITLE
David

### PR DESCRIPTION
**Pull request by DavidSwavey**
Updated code for Academics, Expense, and Class and Sections.

### CODE REVIEW

**Review by RuthBerhane — COMMENTED** [review]
I don't think there needs to be notes in the PageInitializer file like you have it there

**Review by ulyanamazur — APPROVED** [review]

**Review by SergNikole — APPROVED** [review]

**Review by zimaxleto — APPROVED** [review]
reviewed

**Review by ulyanamazur — APPROVED** [review]

**Review by JOYCE-CAG — COMMENTED** [review]
Good job David

**Review by safwan216 — APPROVED** [review]
Looks good to me, good job David!!

**Review by arthuroLP — APPROVED** [review]
looks good

**Review by chromatechacademy — APPROVED** [review]
Approved

**Pull request merged**
