### PR TITLE
invalid credentials login -ready for review 

### PR DESCRIPTION
**Pull request by ulyanamazur**

### CODE REVIEW

**Review by DavidSwavey — APPROVED** [review]
Looks good!

**Review by RuthBerhane — COMMENTED** [review]
You need comment notes on your LoginPage

**Review by safwan216 — CHANGES_REQUESTED** [review]
line 29 of the login page should have a comment to describe the invalidCredentialsText. Looks good otherwise

**Review by safwan216 — APPROVED** [review]
Great job Ulyana, looks good to me

**Review by SergNikole — APPROVED** [review]

**Review by arthuroLP — APPROVED** [review]
looks fine

**Review by SergNikole — APPROVED** [review]

**Review by zimaxleto — APPROVED** [review]
approved

**Comment by chromatechacademy** [comment]
PR closed.  There shouldn't be more than 1 PR open at a time.

**Pull request closed without merging**
