### PR TITLE
Latest changes -Joyce

### PR DESCRIPTION
**Pull request by JOYCE-CAG**
This is AGT 43 and 44 scenario.

### CODE REVIEW

**Review by DavidSwavey — APPROVED** [review]
Looks good. Good work!

**Review by zimaxleto — APPROVED** [review]
Reviewed

**Review by arthuroLP — APPROVED** [review]
looks fine

**Review by safwan216 — APPROVED** [review]
Looks good, great job Joyce!

**Review by RuthBerhane — APPROVED** [review]

**Review by matakevin — APPROVED** [review]
There are a lot of spaces in the 2 classes that are not necessary.  If this issue is not addressed by this PR then it will be in the next.

**Review by matakevin — APPROVED** [review]
Additional spaces will be taken out by David in the following PR - Kevin

**Comment by chromatechacademy** [comment]
Spaces will be removed in the next PR.  Merging to allow others to upload their code also.

**Pull request merged**
